sudo: required
dist: bionic
language: python

python:
  - 3.7


install:
  - echo "install"
  - pip3 install peewee

before_script:
  - echo "Hola"
  - echo "Adios"

script:
  - python3 -m unittest discover -s tests/
