sudo: required
dist: bionic
language: python

python:
  - 3.7

before_install:
  - sudo apt update
  - sudo apt install libgirepository1.0-dev

install:
  - pip3 install wheel peewee pygobject

script:
  - python3 -m unittest discover -s tests/
